### PR TITLE
python3: support basic cross-compilation

### PR DESCRIPTION
**Pull request by notwa**
as an amendment to #640, this roughly restores the includedirs patch from python 2. it also forces timegm as found in the configure command because it wouldn't detect it for some reason, which python would then fail to redefine. the gettext dependency is needed for libintl.

I built a cross-compiler with musl-cross-make for ARM on my x64 sabotage host, then ran the resulting binary in a chroot on my raspi (hardware revision a21041 if it matters). however, I haven't yet tested it more than printing "hello world" in the REPL.

some notes:
* the patch is mostly the result of a sed command. let me know if you would prefer that instead.
* I don't have a darwin host so I can't tell if replacing *all* the checks is a bad idea.
* I didn't check if it could be built without libintl.
* this probably doesn't constitute a rebuild since it concerns build-time stuff.
* I had some build issue relating to getaddrinfo and ipv6, but I can't reproduce it…

### CODE REVIEW

**Comment by notwa** [comment]
ah heck, I just noticed pip and easy_install are missing from the resulting build. lemme iron this out a bit.

**Comment by notwa** [comment]
ok, this seems to be python making astute assumptions about paths again (and not checking dependencies in configure like everyone else) so I'll write a workaround for this in a bit.

**Comment by rofl0r** [comment]
cool, thanks for working on this!
what are the changed lines in the patch, that only concern macos, about ?
e.g.
```diff
- if ismac:
+if ismac and not cross_compiling:
```
the branch will only be taken if it's used on a mac, so adding the new cross_compiling to that shouldn't make any difference for us. or am i missing something ?

**Comment by notwa** [comment]
not sure. it was part of the python 2 patch so I assumed it was something important. I've stripped it all out for the next commit.

okay, I added a hack and zlib is now detected. the wheels for pip and setuptools are present, but ensurepip is seeing the host's packages and skipping installing them. this problem seems to run deeper than just cross-compilation because attempting to run `python3 -m venv subdir` will not install `subdir/bin/pip3.7` either. this is likely due to the pathsearch patch, I'll have to fudge around with it some more.

**Comment by rofl0r** [comment]
> not sure. it was part of the python 2 patch so I assumed it was something important.

ah interesting. that part of the patch was taken from openadk.

> this problem seems to run deeper than just cross-compilation because attempting to run python3 -m venv subdir will not install subdir/bin/pip3.7

virtualenv is pretty broken. is it now part of a base python install ? maybe this helps: https://github.com/pypa/virtualenv/pull/1309 (was later reverted)

**Comment by notwa** [comment]
> virtualenv is pretty broken. is it now part of a base python install ? maybe this helps: [pypa/virtualenv#1309](https://github.com/pypa/virtualenv/pull/1309) (was later reverted)

venv is included with python 3.3+, which implements a subset of virtualenv. I don't think I've run into symlink issues with it, but I don't use it often.

I've written some new getpath.c hacks and now virtual environments seem to work correctly, however ensurepip still won't create /bin/pip3.7 and /bin/setuptools3.7 when cross-compiling. at this point I guess this is normal…? at least, this issue might not be specific to sabotage. I'll probably just wind up creating them by hand if the build script detects them missing, since they mostly just invoke `python3 -m etc`.

`/bin/python3 -m pip` seems to be working after these last few commits. it installs packages to `/opt/python3/lib/python3.7/site-packages` though, which is a little gross. I tried adding an `/etc/pip.conf` with `[global] prefix=/local` but annoyingly, this breaks virtual environments, because it then *always* wants to install to /local.

oh well. I think I'm getting somewhere at least.

aside: I had to manually copy `musl-cross-make/output/arm-linux-musleabi/lib/libgcc_s.so.1` into my cross-sabotage directory for expat (and its python bindings) to work; I'm not sure how to handle this nicely.

**Comment by rofl0r** [comment]
> it installs packages to /opt/python3/lib/python3.7/site-packages though, which is a little gross.

indeed. basically stuff in /opt/package is meant to be read-only.
making the interpreter aware of butch_staging_dir seems to be a bad idea, and precisely what the existing "hacks" attempted to fix.

what precisely is the issue with the pip module without the butch_staging_dir stuff ?

**Comment by notwa** [comment]
force pushed just to clean up some minor mistakes, the commits are largely the same.

> making the interpreter aware of butch_staging_dir seems to be a bad idea, and precisely what the existing "hacks" attempted to fix.
> 
> what precisely is the issue with the pip module without the butch_staging_dir stuff ?

the problem is that python will normally look up from its binary at `/opt/python3/bin/python3.7`, see `/opt/python3/lib/python3.7/os.py` and decide `/opt/python3` is good enough. this is actually the intended behavior for virtual environments, but for sabotage it means it skips checking `/lib` entirely.

my hack detects if the path starts with `/opt/` (or whatever `$butch_staging_dir/` is) and just skips to `PREFIX` or `EXEC_PREFIX`. this is the same action taken as the old hack, but that hack only looked for `/bin/python3` or if argv0 contained `python` and would interfere with venv.

however, pip no longer installs to `/lib`, even though python will read from it. I think I can fix this though.

**Comment by notwa** [comment]
ok, after fumbling around with wide strings for *way* too long, I found the case I wasn't handling and pip seems to cooperate now. this also works in the cross-compiled chroot, although `python3 -m ensurepip` must be run on the target, and I need to fix a quirk with the final symlinks.

**Comment by rofl0r** [comment]
hi @notwa, is this PR complete now ?

**Comment by notwa** [comment]
yeah, I think it's met my original goal of supporting basic cross-compilation. there's still some quirks to iron out, but some of them seem to be inherent with python and someone else might have to work on them.

**Pull request merged**
