### PR TITLE
update ruby to 2.2.3 with new libressl patch

### PR DESCRIPTION
**Pull request by robotanarchy**
Updated ruby to latest version, libyajl builds fine with this ([only package depending on ruby](http://pkg.sabotage.tech/process.cgi?action=pkgoverview&pkg=ruby) except for world and libwebkitgtk1).

The old musl patch isn't required anymore (at least it builds fine without it), but there's a new libressl patch for `RAND_egd()`, similar to the wget one.

(I wanted to port a ruby on rails application, but luckily I've found an alternative :+1:)

### CODE REVIEW

**Comment by robotanarchy** [comment]
oh and I've added disable-docs to save compile time. I think I read this somewhere in the sabotage wiki/COOKBOOK, but I can't find it anymore. Is this good practice here?

**Comment by rofl0r** [comment]
is ruby 2.x backwards compatible ? afaik its a situation similar to perl 5 vs 6, python 2 vs 3, no ?
and yeah, disabliing docs is fine especially if lots of time/space is wasted on generation of html and pdfs, it breaks the build or requires additional deps. what we want installed on sabotage is just manpages.

**Comment by robotanarchy** [comment]
2.0 is fully backwards compatible [(wikipedia)](https://en.wikipedia.org/wiki/Ruby_(programming_language)#Ruby_2.0):
> Ruby 2.0 is intended to be fully backward compatible with Ruby 1.9.3. As of the official 2.0.0 release on February 24, 2013, there were only five known (minor) incompatibilities.

Looks like they started to remove some features in 2.2:
> Features that were made obsolete or removed include callcc, the DL library, Digest::HMAC, lib/rational.rb, lib/complex.rb, GServer, Logger as well as various C API functions.

Also the article says:
> Ruby 1.9 has been obsolete since February 23, 2015,[32] and it will no longer receive bug and security fixes. Users are advised to upgrade to a more recent version.

To be honest, I don't really care which version is in sabotage because I won't use it anyway (as I said before, I tried to port some software that I have found a replacement for). I have even tried to build libwebkitgtk1 to see if anything breaks, but that took forever and failed on some not-to-ruby-related dependency (it built X, gstreamer, basically everything). But as I've done the patch already, I thought I'd do the PR so now work will be duplicated in case someone needs this later.

**Comment by rofl0r** [comment]
nice i was just asking because i thought it may make sense to call the package ruby2 oslt in case they're not compatible

**Pull request merged**
