### PR TITLE
xkbcomp: add missing prerequisite libxdmcp

### PR DESCRIPTION
**Pull request by rhencke**

### CODE REVIEW

**Comment by igzivkov** [comment]
Where do you see xkbcomp requiring libxdmcp?

**Comment by rhencke** [comment]
When attempting to build xkbcomp from a clean stage1 environment, it fails with:
```
...
gcc -std=gnu99 -I/include   -DDFLT_XKB_CONFIG_ROOT='"/share/X11/xkb"' -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -fno-strict-aliasing -Wbad-function-cast -Wformat=2 -Wold-style-definition -Wdeclaration-after-statement  -D_GNU_SOURCE -fdata-sections -ffunction-sections -Os -g0 -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -ftree-dce  -s -Wl,--gc-sections -Wl,-z,relro,-z,now -o xkbcomp action.o alias.o compat.o expr.o geometry.o indicators.o keycodes.o keymap.o keytypes.o listing.o misc.o parseutils.o symbols.o utils.o vmod.o xkbcomp.o xkbparse.o xkbpath.o xkbscan.o -lX11 -L/lib -lxkbfile   -lX11 -lxcb -lXau -lXdmcp
/bin/ld: cannot find -lXdmcp
collect2: error: ld returned 1 exit status
make[2]: *** [xkbcomp] Error 1
make[2]: Leaving directory `/src/build/xkbcomp/xkbcomp-1.2.1'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/build/xkbcomp/xkbcomp-1.2.1'
make: *** [all] Error 2
```

**Comment by igzivkov** [comment]
It should be added to libxcb's prerequisites as that is the only package in the dependency chain which uses libxdmcp (optionally).

**Comment by rhencke** [comment]
Ah, my bad, thanks.  I'll close this one and put up a corrected one soon.

**Pull request closed without merging**
