### PR TITLE
New package f2fs-tools

### PR DESCRIPTION
**Pull request by bkauler**
This is the first time that I have ever done a pull request with git!

I'm using SmartGit, turns out to be a very nice tool, works on Windows, Mac and Linux. For any other git newbie, I have documented my steps to setup SmartGit on the Puppy Forum:
http://murga-linux.com/puppy/viewtopic.php?t=106704

I cloned sabotage-linux/sabotage, created a local branch, tested that my f2fs-tools build works, then merged my local branch back into local master.

Then I attempted a push, which failed. I hadn't realised that I needed to fork sabotage-linux/sabotage. So I did that, bkauler/sabotage, cloned it with SmartGit, then was able to merge the local clone of sabotage-linux/sabotage into local bkauler/sabotage, then was able to push to remote bkauler/sabotage.

Whew! But have it figured out now, so now doing a pull request.

f2fs-tools is utilities for the f2fs filesystem, great for Flash sticks. But of course to use it, f2fs support has to be enabled in the kernel.

There is a patch to include queue.h in the package source.

### CODE REVIEW

**Comment by rofl0r** [comment]
i noticed that there is https://dev.gentoo.org/~blueness/f2fs-tools/f2fs-tools-1.6.1.tar.xz
it ships with a configure script so that would save us from the automake/libtool deps...

**Comment by rofl0r** [comment]
of course it would be better if upstream shipped proper release tarballs...

**Comment by rofl0r** [comment]
hi barry! did you see my comments ?

**Comment by bkauler** [comment]
Regarding the 'configure' missing from f2fs-tools, unfortunately, there are rather a lot of source packages in the same situation.

Also, I am reluctant to use a source package that is not from the original package maintainers.

**Comment by bkauler** [comment]
I tried to compile the source pkg from gentoo, in the sabotage build environment. Same recipe as before.

Unfortunately, it is hardcoded to need automake-1.15.
This happens sometimes, when someone uses the tools to create a 'configure' script.

So the autoreconf would have to be run anyway.

**Comment by bkauler** [comment]
I will close this pull request.

I am working on bkauler/sabotage so that package builds targeting Quirky Linux or Puppy Linux will in no way conflict with the sabotage-linux/sabotage master branch.
When I have got that ready, I will submit another pull request.

As to f2fs-tools, I suggest just accept it as-is. If later on, a source package can be created that does not need libtool etc, that's fine.
f2fs-tools will also be in the upcoming pull request.

**Comment by rofl0r** [comment]
ok, nice idea. i think we should contact the f2fs-tools maintainers and ask them to include sys/queue.h in their include dir so we dont have to put it into sabotage (the header is a standalone library with a more restrictive license than the sabotage one due to the advertising clause)

**Comment by rofl0r** [comment]
i have now added a package queue-h, which gets the header from the freebsd repo instead of putting it into KEEP.

**Pull request closed without merging**
