### PR TITLE
add efi bootloader manager

### PR DESCRIPTION
**Pull request by soul9**
* Efivars and efibootmanager are tools used to manipulate the UEFI boot entries. Efibotmgr is needed to install sabotage on an UEFI system without having to manually add the boot entry in the "bios" (if this is even possible, not all bioses have an entry editor)
 * the kernel package updates the modules.* files in /lib/$kver now (for modprobe)
 * dhclient's behavior was not reliable. this setup works far better for me.
 * initramfs wait time: some flakey usb key took more than 10 seconds to show up on one of my systems, so I hope 20 seconds should suffice for most use cases

### CODE REVIEW

**Comment by soul9** [comment]
@rofl0r 
re depmod: as much as that is true, all it does is create .../lib/modules/$kver/modules.* files for modprobe to work. Without this modprobe will not work until you run depmod. It doesn't mess with loading modules or anything like that.
re dhclient: the behavior is not uniform: it backgrounds on success and not on failure. I think the wpa script should also make sure there is no other dhclient running for that interface. Sure an option can be added, I am surprised that dhclient works fine for you, though, since I've booted sabotage on a variety of machines and all of them exhibit the issue where dhclient only gets an address on the second run (I've also seen a machine where it works only on third run).
udhcpc can not be foregrounded completely because it flushes the network configuration on exit, so this was the simplest uniform behavior I could come up with.

**Comment by rofl0r** [comment]
as for the changes to dhclient, we could add a command line flag "-nw" (nowait) that activates the daemon mode such as the "official" dhclient does: http://linux.die.net/man/8/dhclient
seems cleaner than to change the behaviour silently or adding a "secret" env var

**Comment by soul9** [comment]
sounds good. i'll do this soon

**Comment by soul9** [comment]
dhclient updated with -nw flag

**Comment by soul9** [comment]
are you waiting for something else regarding this pr?

**Comment by rofl0r** [comment]
did you get around to look at musl's configure script for elegant command line arg parsing ?
i'd like to see support for flags like timeout, retries and then make the wpa action script make use of them explicitly

**Comment by bitshark** [comment]
Hey guys -- just a couple of notes and comments...   Just disregard if you've heard any of this already...

- Initramfs

My opinion is the only reason to use initramfs is if you (1) need cryptdisks support at boot, (2) have custom software RAID configuration, (3) want to locate your root mount by UUID, (4) need special root filesystem (F2FS) support not configured in the kernel but exists as module, and so on.

Currently I don't use initramfs on Sabotage, but I probably will soon.  I always write my own initramfs when I need one , and I try to avoid making it slow......

The wait time / lag on USB devices in initramfs is avoidable --  Some USB hardware is slow...  My trick is load the critical stuff from initramfs and leave the rest for later when there is more than one PID.  I grant/veto devices in initramfs through control of their kernel modules.

- Dhclient

I support the idea of increasing the number of default retries on dhclient ...   Then the forking to background on success makes sense.  Currently, I must run dhclient eth0 between 2 and 3 times to get an address.  

- UEFI 

I just picked up a Dell which had Win8 and UEFI... It's my Sabotage box...For simplicity I set everything to Legacy (MBR) mode.  But UEFI would be nice for the GPT partitions on the SSD.  I think I'd use that.

- Depmod

This is a good idea , most people will forget to run depmod.  Put it right into the kernel package build script and you'll have all the kernel module metadata ready to go.

Great work, I'm really enjoying this distro.

**Comment by soul9** [comment]
the wait/lag only happens when the device is not found. i.e. if your device is there at boot there will be no delay at all. I don't understand your paragraph that starts with 'The wait time / lag on USB devices'

**Comment by bitshark** [comment]
Okay I think I misunderstood... I thought you meant that after loading appropriate module and mdev or udev.... That you are still waiting in your /init shell script for some flakey USB device that's causing your boot to hang ...  

Instead I suspect you mean some sort of dynamic USB device?    Like I insert a USB device during the boot sequence for cryptsetup that contains a keyfile for LUKS?   Or I insert a USB device during boot that serves as my root partition?    

Anyway, just disregard what I've written because I don't think it applies to the issue you were referring to.   I just meant that I try to compile my kernels with lots of modules, then I load these as necessary in initramfs.    So if I need to mount root on a USB I load usb_storage.ko ...  

Anyway good updates, thanks for all the hard work everyone

**Comment by soul9** [comment]
I think we have most stuff compiled in by default. I do copy modules into the initramfs, so if mdev autoloads them it should be fine. and yes, this timeout waits for a specific device, it doesn't sit around waiting.

**Comment by soul9** [comment]
@rofl0r would something like https://github.com/sabotage-linux/sabotage/blob/master/KEEP/initramfs.init#L54 and https://github.com/sabotage-linux/sabotage/blob/master/KEEP/initramfs.init#L63 be ok? imho pretty much the same thing as http://git.musl-libc.org/cgit/musl/tree/configure#n133

**Comment by rofl0r** [comment]
the options to dh-client should use the same syntax as the "upstream" one (and that one doesn't use = to pass values)

**Comment by soul9** [comment]
yeah, except dh is debhelper and thank god there is no debhelper on sabotage ;)

**Comment by rofl0r** [comment]
i merged most of your commits manually ( https://github.com/sabotage-linux/sabotage/compare/0101ffb9469d...93725f2b2f19 ), except 7621fa8539 which gave a merge conflict (please redo on current master) and the dhclient commit which we should polish a bit more

**Pull request closed without merging**
