### PR TITLE
honor opt*flags in stage1 builds

### PR DESCRIPTION
**Pull request by soul9**
the main goal of this is to make stage1 build honor opt*flags set in butch_optflags
and adds a HARDENED and STATIC option to butch_optflags
this also fixes some cross-build issues

### CODE REVIEW

**Comment by rofl0r** [comment]
can we leave the optflags change out for the moment as well ?

**Comment by soul9** [comment]
I have net tested with the original mess of flags. sorry.

**Comment by rofl0r** [comment]
original mess of flags ?

btw the -static for mpc, mpfr, gmp shouldnt be needed since they're only libraries

**Comment by soul9** [comment]
but you do want to build them statically no?

**Pull request closed without merging**
