### PR TITLE
xf86-video-intel: fix module load error

### PR DESCRIPTION
**Pull request by henriqueleng**
Had similar problem a long time ago, intel module fails to load when Xorg starts.  Removing this line solved the problem.

### CODE REVIEW

**Comment by rofl0r** [comment]
interesting. i use the intel driver and it works well.
what was the error message you were getting ?
probably there's just a dependency missing...

**Comment by henriqueleng** [comment]
I was receiving the same old message I got a long time a go, the last time I used sabotage
it is:
 _drv.so: Error relocating ...                                    I810InitMC: symbol not found.

**Comment by rofl0r** [comment]
i analyzed the problem with another user in the chat and it turned out it's due to some missing deps, while the fix proposed by you did not work.
can you add a new PR for your other unrelated commits ? thanks!

**Comment by rofl0r** [comment]
oh i see you already have the other 2 commits in the other PR. nevermind then.

**Pull request closed without merging**
