### PR TITLE
RFC: add kernel54

### PR DESCRIPTION
**Pull request by jonlap**
Here's Linux kernel 5.4.31. There are some changes I though might be worth going through first:

add kernel54 as new optional longterm kernel
- build section is copied from kernel414 package and only has required changes to make it compile. I suppose I could have done everything in kernel414 build section to avoid duplication but I feel it was better this way.
- I "fixed" linux-timeconst-nobc.patch which didn't apply. It builds and resulting kernel works but I would still like someone more familiar with Kbuild to take a look and confirm I didn't break anything.
- at the end of kernel 414 build section, headers_install is run because grsec. Because some "improvements" in build system, headers_install now requires rsync. I changed this part to only do make headers and use find+install to move headers to dest. Now, I haven't been following what's going on with grsecurity lately but I've understood the patch set is now commercial, previous work has ended up living in unofficial forks and some functionality is now in kernel. I do not know if the extra headers step is required at all anymore?

kernel54: remove maybe possibly obsolete headers_install
- this drops the above mentioned extra header hassle

kernel54: override default config
- This is just a convenience thing. In a nutshell if $linux_config is set when running butch install/rebuild, its value is used as a full path to kernel configuration file which will be used instead of the provided default in KEEP. If it's not set, as is the default, provided default configuration is used so no change in default behavior. I did this because I have a single host with single sabotage chroot which I use to build kernels for multiple hardware which all require some customization. Passing custom kernel config to use in kernel package build makes it both cleaner and more straightforward to manage and package all that. I can also set those custom kernel configurations as default (by exporting $linux_config=/what/ever) on systems that require it and thus their configs will be automatically used when updating kernel54. It's only a couple of lines so it can be easily merged into 4.x packages too, if wanted. Another way to achieve something similar would be some consistent naming rules for custom configs with matching rules in .gitignore and kernel54 but I think this is more straightforward and practical way.

So, everything is build and boot tested OK on real x86 hardware with both $K/linux.config and couple of my own configs so it's ready for merging as-is if there's nothing to comment/change. Commits should be easily cherry picked and applied if you don't want/need them all.

### CODE REVIEW

**Comment by rofl0r** [comment]
nice work. did you see the include directive used by pkg/kernel419 ?
we may do the same thing with kernel54, and add some conditional code to the base pkg (kernel414) depending on LINUX_VER.

good catch re headers_install, i believe we don't need it anymore as we use the kernel-headers package anyways.

**Comment by jonlap** [comment]
Done. If there's anything you want changed or have questions let me know. I decided to split the patch to avoid unnecessary duplication and simply used k_major to get the right patch applied. I tested linux-timeconst-nobc-kbuild5.patch with 5.7-rc1 and it applies so I think for now there's no need for more sophisticated version matching.

I noticed wireless regulatory database part was not working as expected in 4.19 and later because, surprise, things got improved in 4.15 meaning the feature to include plaintext db.txt in kernel was removed and replaced with feature to read regulatory.db binary as a firmware. It should be fixed now, at least according to dmesg output.

I intentionally didn't bump kernel49 package version. Might save someone from one unnecessary kernel compile.

**Comment by rofl0r** [comment]
cool.
the regdb thing is disturbing, where are you getting the binary files from ?
is there a way we could compile it ourselves from regdb.txt ?

**Comment by jonlap** [comment]
Ah, sorry, should have been more verbose whats happening there. Binary and its detached signature are from [wireless-regdb git](https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git) repository master. Binary is signed (regulatory.db.p7s is the signature) and key to check it against comes with kernel (and is built into it) so it's as "safe" as including any other signed blob but at least its the official source for the whole regdb. 

It is possible to build (and use our own signatures etc.) that binary ourselves but that seems to depend on all sorts of stuff, like python, so imo should not be part of a kernel build. These are the options I can think of:

- Keep it as it is with these commits (=include signed binary from supposedly trustworthy source as extra firmware in kernel) which is functionally the same as the previous way to do it.
- Package and build wireless-regdb (this will need to install to same location as linux-firmware as blob needs to be somewhere firmware loader can find it)
- Include binary in linux-firmware
- See if we can easily revert commit c8c240e284b3d821011b4f680b3eaa99569b3756 to continue using the old way of embedding regdb. Probably begging for trouble in the long run.

**Comment by rofl0r** [comment]
thanks for your investigation.

> Keep it as it is with these commits (=include signed binary from supposedly trustworthy source as extra firmware in kernel) which is functionally the same as the previous way to do it.

that's not entirely accurate, our regdb.txt is patched to allow higher tx power and additional channales in an imaginary country "HX" which can be legally used in international waters.
i'd rather not include binary stuff like this in sabotage itself since it might become hard to check its origin further on in the future.
also i find it rather practical to have the regdb built into the kernel rather than in a separate file in /lib/firmware.

> See if we can easily revert commit c8c240e284b3d821011b4f680b3eaa99569b3756 from kernel to continue using the old way of embedding regdb. Might be begging for trouble in the long run. I can test this later if needed.

this seems like the best option, imo. maybe a "wifi hacker distro" like kali linux even has a forward-ported patch prepared already?

> It is possible to build (and use our own signatures etc.) that binary ourselves but that seems to depend on all sorts of stuff, like python

if the reversal of c8c... appears to be too problematic we might investigate whether this process can be improved.

**Comment by jonlap** [comment]
> > Keep it as it is with these commits (=include signed binary from supposedly trustworthy source as extra firmware in kernel) which is functionally the same as the previous way to do it.
> 
> that's not entirely accurate, our regdb.txt is patched to allow higher tx power and additional channales in an imaginary country "HX" which can be legally used in international waters.

Didn't know that, cool!

> i'd rather not include binary stuff like this in sabotage itself since it might become hard to check its origin further on in the future.
> also i find it rather practical to have the regdb built into the kernel rather than in a separate file in /lib/firmware.

Agreed.

> > See if we can easily revert commit c8c240e284b3d821011b4f680b3eaa99569b3756 from kernel to continue using the old way of embedding regdb. Might be begging for trouble in the long run. I can test this later if needed.
> 
> this seems like the best option, imo. maybe a "wifi hacker distro" like kali linux even has a forward-ported patch prepared already?

Couldn't find anything. Fortunately it was quite simple to revert and required only one additional ifdef  in code to make it play nice.

I added squashed patch with revert + fixes to KEEP which is applied if kernel is 4.19 or newer. Patch applies to both 4.19 and 5.4. It's configurable and if disabled regdb is loaded as firmware instead. I build and boot tested 4.14, 4.19 and 5.4. I tested changing country with "iw reg get ; iw reg set FI ; iw reg get" and it changes values properly with all kernels.

**Comment by rofl0r** [comment]
> Fortunately it was quite simple to revert and required only one additional ifdef in code to make it play nice.

that's great, nice work!

> Should I clean this up into one or two commits and send another PR?

hmm indeed, this would avoid having the binaries in the commit history.

how about roughly the following commit history:

kernel414: override default config 
kernel414: remove maybe possibly obsolete headers_install 
add kernel54 and handle build in kernel414
kernel54: kernel414: split timeconst-nobc patch
kernel54: kernel49: use split nobc patches 
kernel54/kernel419: restore support for internal regdb
kernel54: add required config options
kernel54: bump to 5.4.33

**Comment by rofl0r** [comment]
thanks again, finally found the time to polish up this PR.
merged as f4768f6b...64b0a32b

note that there are some tiny differences to your branch but it is functionally identical.

**Comment by jonlap** [comment]
@rofl0r Great, thanks! Been so busy lately I forgot to finish the whole thing, sorry about that!

**Pull request closed without merging**
